openapi: 3.0.3
info:
  title: Exvs Search XB
  description: Exvs Search XB用API
  version: 1.0.0
servers:
  - url: https://localhost:8080/api/v1
tags:
  - name: Airframe
    description: 機体情報関係
paths:
  /airframes:
    get:
      tags:
        - Airframe
      summary: 機体情報の一覧取得
      description: 機体情報の一覧取得
      operationId: getAirframes
      security:
        - Authorization: []
      parameters:
        - name: offset
          required: true
          in: query
          allowEmptyValue: true
          description: |
            機体情報の取得開始位置
          schema:
            type: integer
        - name: limit
          required: true
          in: query
          allowEmptyValue: true
          description: |
            機体情報の取得数
          schema:
            type: integer
        - name: airframeName
          required: true
          in: query
          allowEmptyValue: true
          description: |
            機体名の検索
          schema:
            type: string
        - name: cost
          required: true
          in: query
          allowEmptyValue: true
          description: |
            機体コスト
          schema:
            type: integer
        - name: titleOfWork
          required: true
          in: query
          allowEmptyValue: true
          description: |
            作品タイトル名
          schema:
            type: string
        - name: awakenType
          required: true
          in: query
          allowEmptyValue: true
          description: |
            覚醒タイプ名
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas/requests/getAirframesResponse.yaml"
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
